// Bundles every analysis/*.md note into app/notes-data.js so the app is
// fully self-contained (no fetches, works offline from any static host).
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const ANALYSIS = path.join(ROOT, 'analysis');
const OUT = path.join(__dirname, 'notes-data.js');

function walk(dir) {
  const out = [];
  for (const e of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...walk(p));
    else if (e.name.endsWith('.md')) out.push(p);
  }
  return out;
}

function titleOf(rel, body) {
  const m = body.match(/^#\s+(.+)$/m);
  if (m) return m[1].trim();
  return path.basename(rel, '.md').replace(/_/g, ' ');
}

const notes = walk(ANALYSIS).map((p) => {
  const rel = path.relative(ANALYSIS, p).split(path.sep).join('/');
  const body = fs.readFileSync(p, 'utf8');
  return { p: rel, t: titleOf(rel, body), b: body };
});

const papers = [];
const PQ = path.join(ROOT, 'previous_year_questions');
for (const e of fs.readdirSync(PQ, { withFileTypes: true })) {
  if (e.isFile() && e.name.toLowerCase().endsWith('.pdf')) papers.push('previous_year_questions/' + e.name);
  if (e.isDirectory()) {
    for (const f of fs.readdirSync(path.join(PQ, e.name))) {
      if (f.toLowerCase().endsWith('.pdf')) papers.push(`previous_year_questions/${e.name}/${f}`);
    }
  }
}
papers.sort();

fs.writeFileSync(
  OUT,
  '// Generated by build.js — do not edit by hand.\n' +
    'window.VAULT = { notes: ' + JSON.stringify(notes) + ', papers: ' + JSON.stringify(papers) + ' };\n'
);
console.log(`Bundled ${notes.length} notes, ${papers.length} past papers -> notes-data.js`);
